version: "3.9"
services:
    api:
        build: .
        ports: 
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=Compaq09!
            - DATABASE_NAME=fastapi
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=dd6214897baa82d25c64817396efc9560f23f7099ad4e8bcaa6cf63b88e8d9a3
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=Compaq09!
            - POSTGRES_DB=fastapi
        volumes:
            - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db: